openapi: '3.0.2'
info:
  title: Sonarqube Web API
  description: The web services composing the [web API](https://next.sonarqube.com/sonarqube/web_api) are documented within SonarQube. To access the documentation, select the help button from the top bar in SonarQube
  version: '2.0'
servers:
  - url: https://sonarcloud.io/api
    description: Sonarcloud.io Web API
paths:
  /issues/search:
    $ref: ./issues/sonarqube-v2.issues.openapi.yml#/paths/~1issues~1search
  /user_tokens/search:
    get:
      responses:
        '200':
          description: OK
tags:
  - name: Web API v2
components:
  parameters:
    p:
      name: p
      description: 1-based page number
      example: 1
      in: query
      schema:
        type: integer
        minimum: 1
    ps:
      name: ps
      description: Page size. Must be greater than 0 and less or equal than 500
      example: 50
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 500
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []  