name: Storybook

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
    
      - name: Install pnpm
        uses: pnpm/action-setup@v4
          
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: 'upload'
        uses: actions/upload-pages-artifact@v3
        with: 
          path: shared/vue-ui/docs
  
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
