# This is a basic workflow to help you get started with Actions

name: Storybook

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: shared/vue-ui/docs
          install_command: pnpm install
          build_command: pnpm build-storybook
